name: onze_cafe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  moyasar: ^2.0.13
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  supabase_flutter: ^2.6.0
  circular_countdown_timer: ^0.2.3
  onesignal_flutter: ^5.2.5
  pinput: ^5.0.0
  animated_snack_bar: ^0.4.0
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  fl_chart: ^0.69.0
  syncfusion_flutter_datepicker: ^27.1.51
  loader_overlay: ^4.0.2+1
  lottie: ^3.1.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/SVG/outlined_cup.svg
    - assets/coffee_bean/
    - assets/illustrations/
    - assets/loading/
    - assets/logo/

fonts:
  - family: Poppins
    fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700